name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
  #       - name: Run tests
  #         run: npm test
  #       - name: Build
  #         run: npm run build

  build-and-push-image:
    needs:
      - build-and-test

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: echo result
          # env:
        # commit_hash: ${{ needs.commit-hash.outputs.commit_hash }}
        run: | 
          echo "The commit hash is ${{ github.repository }}"
          echo "The commit hash is ${{ github }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-24.04
  #   needs:
  #     - build-and-push-image
  #     - commit-hash

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: create env file
  #     run: |
  #       echo "GIT_COMMIT_HASH=${{ github.sha }}" >> env
  #   - name: 'Docker Stack Deploy'
  #     uses: cssnr/stack-deploy-action@v1
  #     with:
  #       name: 'guestbook'
  #       file: 'docker-stack.yaml'
  #       host: zenful.cloud
  #       user: deploytest
  #       ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
  #       env_file: './env'
